[features]
seeds = false
skip-lint = false
[programs.localnet]
to_do_d_app = "4roLsp9UCWbpm9tgj7yw94eDn6jGWJncvLq2fTbZdeWd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/daoist/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
